import { Sparkles, Database, Search, Zap } from 'lucide-react';
import { MessageSource } from '../types';

interface SourceBadgeProps {
  source: MessageSource;
}

export default function SourceBadge({ source }: SourceBadgeProps) {
  const isElasticsearch = source.type === 'elasticsearch';
  const hasDocuments = (source.documentsUsed?.length ?? 0) > 0;
  const isNew = source.type === 'new';

  let label: string;
  let icon: React.ReactNode;
  let colorClasses: string;
  let description: string;

  if (isElasticsearch) {
    label = 'Elasticsearch Cache';
    icon = <Database size={12} />;
    colorClasses = 'bg-purple-50 text-purple-700 border border-purple-200';
    description = 'Retrieved from a previous interaction — no AI call was made.';
  } else if (isNew && hasDocuments) {
    label = 'New AI Response';
    icon = <Sparkles size={12} />;
    colorClasses = 'bg-emerald-50 text-emerald-700 border border-emerald-200';
    description = 'Generated by AI using matched document context.';
  } else if (isNew) {
    label = 'New AI Response';
    icon = <Zap size={12} />;
    colorClasses = 'bg-blue-50 text-blue-700 border border-blue-200';
    description = 'Generated by AI (no matching documents found).';
  } else {
    // Fallback for legacy 'reused' type
    label = 'Cached Response';
    icon = <Search size={12} />;
    colorClasses = 'bg-amber-50 text-amber-700 border border-amber-200';
    description = 'Retrieved from cache.';
  }

  return (
    <div className="inline-flex flex-col">
      <div
        className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium ${colorClasses}`}
      >
        {icon}
        {label}
        {source.confidence !== undefined && (
          <span className="text-[10px] opacity-70">
            ({Math.round(source.confidence * 100)}%)
          </span>
        )}
      </div>
      <span className="text-[9px] text-gray-400 mt-0.5 pl-1">{description}</span>
    </div>
  );
}
